### ISSUE TITLE
fails to build with latest bzip3 1.5.1 release

### ISSUE THREAD

**Issue by david-geiger** [Genivia/ugrep#446]
Hi,

On Mageia Cauldron ugrep fails to build since latest bzip3 1.5.1 release with the following build issue:

> zstream.hpp: In member function 'std::streamsize zstreambuf::next(unsigned char*, size_t)':
zstream.hpp:2629:29: error: too few arguments to function 'int32_t bz3_decode_block(bz3_state*, uint8_t*, size_t, int32_t, int32_t)'
 2629 |             bz3_decode_block(bz3file_->strm, bz3file_->buf, block_size, bz3file_->len) < 0)
      |             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from zstream.hpp:96:
/usr/include/libbz3.h:194:19: note: declared here
  194 | BZIP3_API int32_t bz3_decode_block(struct bz3_state * state, uint8_t * buffer, size_t buffer_size, int32_t compressed_size, int32_t orig_size);
      |                   ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:724: ugrep_indexer-ugrep-indexer.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/ugrep-7.1.1-build/ugrep-7.1.1/src'
make[2]: *** Waiting for unfinished jobs....

Attached full build log:
[build.x86_64.0.20241217050303.log](https://github.com/user-attachments/files/18169539/build.x86_64.0.20241217050303.log)

Regards,
David

**Comment by genivia-inc** [comment]
Thanks for the feedback. I'll take a look and get this fixed.

Please note that libbzip3 is optional for ugrep and is not part of the recommended set of compression libraries for ugrep, because I had problems with bzip3 library changes before that broke the build or caused runtime errors. It is a great library, but I hope the developers can keep the API stable.

**Comment by kspalaiologos** [comment]
Hello! Sorry for the breakage. The library version was updated to slightly change the ABI - it shouldn't be a big issue to update it.

**Comment by kspalaiologos** [comment]
Please see header file comments. The version can be queried via `BZIP3_API const char * bz3_version(void);` during the runtime, as for compile-time - I think that you have to tweak your build system to detect the version available. It's simple with autotools, but I am not sure about CMake & co.

**Comment by genivia-inc** [comment]
@kspalaiologos I will integrate this with autotools. Only allow ugrep to be used with bzip3 when `bz3_decode_block()` takes 5 arguments, which should be the updated bzip3 1.5 or greater. Is that correct?

My thinking is that this is safer from a security point of view.

**Comment by kspalaiologos** [comment]
All good. If you enforce version >=1.5.1 there shouldn't be any more problems with decompression that caused you to move away from the codec (the underlying issue was a problem with the CRC logic)

**Comment by genivia-inc** [comment]
Fixed in [latest commit](https://github.com/Genivia/ugrep/commit/dac5e515e7276064bcb93d91d872eb5465a032e4)

**Comment by david-geiger** [comment]
Confirmed now ugrep build fine with the fix, thanks guys :)

**Comment by genivia-inc** [comment]
Fixed in official update 7.1.2.
