### ISSUE TITLE
Cannot compile with gcc/x86_64-conda-linux-gnu/10.3.0

### ISSUE THREAD

**Issue by korziner** [Genivia/ugrep#227]
Cannot compile with gcc/x86_64-conda-linux-gnu/10.3.0 
```
mv -f .deps/ugrep-ugrep.Tpo .deps/ugrep-ugrep.Po
/home/user/mambaforge-pypy3/bin/x86_64-conda-linux-gnu-c++ -std=gnu++11  -march=native  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/user/mambaforge-pypy3/lib -Wl,-rpath-link,/home/user/mambaforge-pypy3/lib -L/home/user/mambaforge-pypy3/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/lib -L/usr/lib -L/usr/lib -o ugrep ugrep-ugrep.o ugrep-cnf.o ugrep-glob.o ugrep-output.o ugrep-query.o ugrep-screen.o ugrep-stats.o ugrep-vkey.o ugrep-zopen.o -lpthread ../lib/libreflex.a -lzstd -llz4 -llzma -lbz2 -lz -lpcre2-8 
/home/user/mambaforge-pypy3/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ugrep-ugrep.o: in function `Grep::StdInHandler::operator()(_IO_FILE*)':
ugrep.cpp:(.text._ZN4Grep12StdInHandlerclEP8_IO_FILE[_ZN4Grep12StdInHandlerclEP8_IO_FILE]+0xa0): undefined reference to `__fdelt_chk'
/home/user/mambaforge-pypy3/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ugrep-vkey.o: in function `VKey::raw_in(int)':
vkey.cpp:(.text+0x8b): undefined reference to `__fdelt_chk'
/home/user/mambaforge-pypy3/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ugrep-vkey.o: in function `VKey::poll(int)':
vkey.cpp:(.text+0x186): undefined reference to `__fdelt_chk'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:395: ugrep] Error 1
make[2]: Leaving directory '/home/user/distr/ugrep/src'
make[1]: *** [Makefile:466: all-recursive] Error 1
make[1]: Leaving directory '/home/user/distr/ugrep'
make: *** [Makefile:366: all] Error 2
Failed to build ugrep: please run the following two commands:
$ autoreconf -fi
$ ./build.sh

If that does not work, please open an issue at:
https://github.com/Genivia/ugrep/issues
```  
After autoreconf -fi still does not work

**Comment by genivia-inc** [comment]
`fdelt_chk`  is a libc function that is not called or defined by ugrep, so it looks like this is a library linking issue with the linker. You may get this link error when trying to cross compile. To compile, execute `make clean` first, then `./build.sh`.

**Comment by korziner** [comment]
Adding -L/lib64 -lc-2.17 solves the issue. I am able to compile successfully explicitly linking against libc-2.17 as here https://stackoverflow.com/questions/68453991/gcc-linux-64-compiler-version-8-4-on-rhel-7-undefined-symbol-clock-gettimegli
