### ISSUE TITLE
building on earlier macOS versions

### ISSUE THREAD

**Issue by reneeotten** [Genivia/ugrep#130]
while packaging `ugrep` in MacPorts, where we attempt to support as many OS versions as possible, I noticed two issues when building on 10.10 and earlier. 

```./mmap.hpp:104:52: error: use of undeclared identifier 'MAP_ANONYMOUS'``` (see build [log](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/142516/steps/install-port/logs/stdio)).
MAP_ANONYMOUS is the same thing as MAP_ANON, which is defined on earlier systems (back to Mac OS X Tiger 10.4 at least), so this could be easily solved by adding the lines below to ```src/mmap.hpp```:
```
// Back compat for OSX 10.10 and earlier
#ifndef MAP_ANONYMOUS
#define MAP_ANONYMOUS MAP_ANON
#endif
```

would you be willing to accept this patch so that we don't have to carry it forward in MacPorts?

After that the package still fails to build on 10.9 and 10.8 with the error below:
```
In file included from ./cnf.hpp:43:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/list:227:9: error: field has incomplete type 'GrepWorker'
    _Tp __value_;
        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:2023:27: note: in instantiation of template class 'std::__1::__list_node<GrepWorker, void *>' requested here
                 decltype(__is_constructible_test(declval<_Tp>(), declval<_Args>()...))
                          ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:2072:14: note: in instantiation of template class 'std::__1::__is_constructible<false, std::__1::allocator<std::__1::__list_node<GrepWorker, void *> >>' requested here
    : public __is_constructible<is_scalar<_Tp>::value || is_reference<_Tp>::value,
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:2098:14: note: in instantiation of template class 'std::__1::__is_constructible_void_check<false, std::__1::allocator<std::__1::__list_node<GrepWorker, void *> >>' requested here
    : public __is_constructible_void_check<__contains_void<_Tp, _Args...>::value
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:2578:34: note: in instantiation of template class 'std::__1::is_constructible<std::__1::allocator<std::__1::__list_node<GrepWorker, void *> >>' requested here
    : __is_nothrow_constructible<is_constructible<_Tp, _Args...>::value, _Tp, _Args...>
                                 ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:2700:14: note: in instantiation of template class 'std::__1::is_nothrow_constructible<std::__1::allocator<std::__1::__list_node<GrepWorker, void *> >>' requested here
    : public is_nothrow_constructible<_Tp>
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/list:839:20: note: in instantiation of template class 'std::__1::is_nothrow_default_constructible<std::__1::allocator<std::__1::__list_node<GrepWorker, void *> > >' requested here
        _NOEXCEPT_(is_nothrow_default_constructible<__node_allocator>::value)
                   ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:332:34: note: expanded from macro '_NOEXCEPT_'
#  define _NOEXCEPT_(x) noexcept(x)
                                 ^
ugrep.cpp:3068:3: note: in instantiation of exception specification for 'list' requested here
  GrepMaster(FILE *file, reflex::AbstractMatcher *matcher, Matchers *matchers)
  ^
ugrep.cpp:3063:8: note: forward declaration of 'GrepWorker'
struct GrepWorker;
       ^
```

It does work though for on earlier OS versions where we use a newer, MacPorts provided `clang`. So likely this is a C++/C++11 feature that isn't fully supported by the Apple clang versions on 10.9 [Apple LLVM version 6.0 (clang-600.0.57)] and 10.8 [Apple LLVM version 5.1 (clang-503.0.40)]. 

I am not familiar enough to understand how to resolve this (if possible at all) or what is the exact feature that is used here that clang doesn't like - do you have any insights? If needed, I can always blacklists Apple clang versions (provided we know which is the earliers version that supports this) and force a newer compiler to build this on 10.9 and 10.8.

Thanks!

**Comment by genivia-inc** [comment]
Thank you for your feedback and helping out! I love MacPorts (and homebrew).

This patch for `mmap.hpp` will be included in the next release:

```
#if defined(HAVE_MMAP) && MAX_MMAP_SIZE > 0
# include <sys/mman.h>
# include <sys/stat.h>
# include <limits>
# ifndef MAP_ANONYMOUS
#  define MAP_ANONYMOUS MAP_ANON
# endif
#endif
```

I have to take a closer look at the error with a `_NOEXCEPT_` in the `list` of `GrepWorker`. The ugrep source uses some C++11 features. This compilation problem looks odd to me. I think you're right about the C++11 feature support in old clang versions.

**Comment by reneeotten** [comment]
thanks @genivia-inc fair enough - I certainly don't understand enough C++ (or much to be honest) to understand these subtleties. Perhaps I'll ask someone else at the MacPorts side to see if this indeed appears to be a clang bug or I'll just figure out which `clang` versions to blacklist to get it to build on the older systems. Just to be sure, this should be all valid in C++11 right, or does it use (experimental) features from a later standard?

**Comment by genivia-inc** [comment]
I've tried to replicate this with [Compiler Explorer](https://godbolt.org/) using Clang 6.0 -std=c++11 with simplified code (see below). Clang has no issues with the simplified code for Clang 4.0 and up.

Perhaps the STL library is to blame for this error? The compilation error occurs in `/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/list:227:9`, which is probably an Apple-specific clone of the STL. If so, this is probably a `<list>` header code/implementation issue.

The simplified code:
~~~
#include <iostream>
#include <list>
#include <exception>

struct Grep {
  void search() { std::cout << "searching...\n"; }
};

struct GrepWorker;

struct GrepMaster : public Grep {
  GrepMaster(int state) : state(state) {}
  void addjob(int job) { workers.emplace_back(job); }
  std::list<GrepWorker> workers;
  int state;
};

struct GrepWorker : public Grep {
  GrepWorker(int job) : job(job) { }
  int job;
};

int main() {
  try {
    GrepMaster server(3);
    server.addjob(7);
  }
  catch (...) {
      std::cerr << "exception\n";
  }
}
~~~

**Comment by reneeotten** [comment]
> I've tried to replicate this with [Compiler Explorer](https://godbolt.org/) using Clang 6.0 -std=c++11 with simplified code (see below). Clang has no issues with the simplified code for Clang 4.0 and up.

From your comment above do I read it correctly that one should be using the `-std=c++11` flag? In the builds `-std=gnu++11` is added instead, would that cause the problem? I apologize for not being too well versed in all of this to fully understand what you mean...

**Comment by genivia-inc** [comment]
Option `-std=gnu++11` versus `-std=c++11` shouldn't matter for this issue. It affects something else (GNU extensions that aren't strictly following the C++ standard).

**Comment by genivia-inc** [comment]
I wonder if there any update on this issue. It seems to me that this is not a compiler bug in an older Clang version but a problem with STL in the XCode bundle. MacOS does not use GNU STL for its implied licensing requirements. There are several posts on the web e.g. SO with questions about the C++ libraries on MacOS, where they live, and how to use GNU libraries and STL, etc.

**Comment by reneeotten** [comment]
@genivia-inc I just updated `ugrep` to version 3.3 and blacklisted Xcode Clang versions < 700. It will install and use a newer Clang (version 9.0 from https://clang.llvm.org/) and use that to compile `ugrep`, which works and it not builds successfully on MacPorts' buildbots all the way down to OS X 10.6. 

I don't have the knowledge and to be honest neither the interest to spend more time in trying to find out the root cause of this. So as far as I am concerned this issue is resolved. If we do figure out a way to have it compile with the "default" Xcode compiler I'll report back here.

**Comment by genivia-inc** [comment]
Thanks for the update! I will close this issue for now if that's OK. Feel free to reopen if there is a way to move forward to address this legacy Clang issue.
